- hosts: qa
  vars:
    variable1: "PlayBookValue"
  vars_files:
    - variables.yml
  tasks:
    - name: Execute Shell Commands
      shell: uname
      register: uname_result
    - debug: msg="Hello {{uname_result}}"
    - debug: msg="Hello {{uname_result.stdout_lines}}"
    - debug: msg="Variable {{variable1}}"